# Dependencies
markdown:            kramdown
highlighter:         rouge

syntax-highlighting:
  enabled : true
  css: syntax.css

pygments_options: ['lineanchors']

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:            WenKu
tagline:          'A library technology blog'
description:      'I discovered me in the library. --Ray Bradbury'
url:              http://www.wenku.ws

author:
  name:           'David Jiao'
  url:            http://twitter.com/djiao
  gravatar:       https://en.gravatar.com/djiao
  photo:          http://1.gravatar.com/avatar/3753f3aa8631c46c0e51525edf9bbbd7?size=120
  introduction:   'Finding Structure in Unstructured Data'

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/jiaola/jiaola.github.io

gems:
  - jekyll-gist
  - jekyll-paginate
